# Generated by Django 5.1.5 on 2025-02-14 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='chicken',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ham',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='mushrooms',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='onions',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pepperoni',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='peppers',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pineapple',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizza_app.crust'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizza_app.topping'),
        ),
    ]
