# Generated by Django 5.1.5 on 2025-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_crust_topping_remove_pizza_chicken_remove_pizza_ham_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ManyToManyField(to='pizza_app.pizza'),
        ),
    ]
