# Generated by Django 5.1.5 on 2025-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_cheese_price_crust_price_pizzasize_price_sauce_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
